### ISSUE TITLE
warning C28251: Inconsistent annotation for function

### ISSUE THREAD

**Issue by Riadela** [boostorg/winapi#78]
When I'm building my solution in release mode I keep getting this warning which is treated as an error.
Specifically it happens in some files in the winapi folder, such as get_last_error.hpp, on the GetLastError function

I dont want to use pragma disable warning on my projects, does anyone have any idea of why this happens..?

**Comment by Lastique** [comment]
1. What Windows SDK and compiler are you using?
2. Can you identify the difference between Boost.WinAPI and Windows SDK declarations?

As a workaround you can define `BOOST_USE_WINDOWS_H` when building your code to force Boost.WinAPI use `windows.h` instead of declaring functions and types on its own.
