### ISSUE TITLE
basic_types.hpp includes <winerror.h>

### ISSUE THREAD

**Issue by pdimov** [boostorg/winapi#81]
There are reports that `<boost/system/error_code.hpp>` breaks code using `NO_ERROR`; the reason is that `winapi/error_codes.hpp` includes `winapi/basic_types.hpp` which includes `<winerror.h>` which defines all error codes as macros, including `NO_ERROR`.

It's not clear why `<winerror.h>` is included; `winapi/error_codes.hpp` defines the error codes as non-macros and does not rely on the macros.

**Comment by Lastique** [comment]
Every user of Boost.WinAPI must still be prepared for any macros that might be defined by Windows SDK. This is because `windows.h` may still be included, either by user or by Boost.WinAPI itself.

As to why `basic_types.hpp` includes `winerror.h`, I'm not sure. Probably, this is a remnant from times when there was no `error_codes.hpp` header. I can probably remove that include, although it might break someone. I'll probably do that after the release.

**Comment by pdimov** [comment]
Reminder.

**Comment by Lastique** [comment]
Thanks.
